export const HANDLE_NAME = 'HANDLE_NAME'
export const HANDLE_EMAIL = 'HANDLE_EMAIL'
export const HANDLE_COMPANY = 'HANDLE_COMPANY'
export const HANDLE_CITY = 'HANDLE_CITY'
export const HANDLE_PASSWORD = 'HANDLE_PASSWORD'



export const CHANGE_HANDLER = 'CHANGE_HANDLER'
export const SUBMIT_HANDLER = 'SUBMIT_HANDLER'
